### ISSUE TITLE
Create gRPC proxy client and server implementation

### ISSUE THREAD

**Issue by tzdybal** [rollkit/go-execution#12]
gRPC proxy client and servers should be implemented for execution API. This is very similar to approach in go-da.
Proxies will be used by rollkit and API implementations to unify communication.

**Comment by ProgramCpp** [comment]
@tzdybal is there a separate issue to add json-rpc proxy client/server? could you add some implementation details like connection management or any package in mind for json-rpc  communication? 

how does the execution layer client choose a rpc package of its choice? say go-ethereum/rpc

**Comment by tzdybal** [comment]
Late to the party: We already have JSON-RPC proxy implemented in #9.

Execution layer implementations can use whatever they want/need - because of gRPC proxy use in rollkit, we avoid all dependency issues.

**Comment by tzdybal** [comment]
Resolved by #9.

**Comment by tzdybal** [comment]
Reopening, as proxy in #9 is not what intended.

**Comment by jim380** [comment]
> Reopening, as proxy in #9 is not what intended.

Could you elaborate please? What was not intended in #9 and what changes would you like to see? Cc: @ProgramCpp

**Comment by tzdybal** [comment]
OK, I'm re-closing. Sorry for the confusion.
